### PR TITLE
Fix update command

### LINKED ISSUE #28: Fix update command
It doesn't check the output of the command, just the exit code... it should check if
```ts
error == null && !stdout.includes('up to date')
```

### PR DESCRIPTION
**Pull request by samollari**
It will now only restart if it wasn't up to date already, the intended behavior (closes #28)

### CODE REVIEW

File: triggers/commands/update.ts [hunk 1]
```diff
@@ -14,12 +14,11 @@ module.exports = <Command> {
...
     if (message) message.channel.startTyping();
-    let process = exec('git pull', (error, stdout, stderr) => {
+    exec('git pull', async (error, stdout, stderr) => {
         console.log({error, stdout, stderr});
-    });
-    process.on('close', async code => {
         message.channel.stopTyping();
-        if (code == 0) {
+        await message.channel.send('```\n' + stdout + '\n``````\n' + stderr + '\n```');
+        if (error == null && !stdout.includes('up to date')) {
```
Comment (Muirrum) [inline triggers/commands/update.ts:21]: Can you explain these changes more?

**Review by Muirrum — DISMISSED** [review]

File: triggers/commands/update.ts (hunk 1 above)
Comment (samollari) [reply triggers/commands/update.ts:21]: Before, it would only look at the exit code of git, which would be 0 if there wasn't a merge problem. However, this didn't check if it was up to date (in which case we have no need to restart), so it now checks if Git doesn't report up to date and there wasn't an error

**Comment by EarlJr53** [comment]
@i-am-gizm0 Since this PR is marked as Open and Auto-Merge is enabled, are you just waiting for a review before we merge it?

**Comment by samollari** [comment]
Yeah Owen wanted me to explain it but if it makes sense enough to you go ahead and merge approve it

**Review by EarlJr53 — APPROVED** [review]
I trust you, it looks like it should work. Although I don't hold any liability if it breaks.
